service: aws-lambda-typescript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: src/handlers.handler
    events:
      - http:
          path: /
          method: GET
          cors: true

plugins:
  - serverless-plugin-typescript